# Production override for Ubuntu ARM64 deployment.
# Usage: docker compose -f compose.yaml -f compose.prod.yaml up -d

services:

  mlflow:
    platform: linux/arm64
    restart: always

  postgres:
    platform: linux/arm64
    restart: always

  airflow-webserver:
    platform: linux/arm64

  airflow-scheduler:
    platform: linux/arm64

  airflow-init:
    platform: linux/arm64

  inference-api:
    platform: linux/arm64
    restart: always

  streamlit:
    platform: linux/arm64
    restart: always
