services:
  gateway-api:
    ports:
      - "${GATEWAY_PORT}:8100"
    volumes:
      - ../api/gateway_api:/app
      - ../src:/app/src
      - ../configs:/app/configs
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8100",
        "--reload",
        "--reload-dir",
        "/app",
        "--reload-dir",
        "/app/src"
      ]

  streamlit:
    ports:
      - "${STREAMLIT_PORT}:8501"
    volumes:
      - ../apps/ml_platform:/app
    command:
      [
        "streamlit",
        "run",
        "app.py",
        "--server.port=8501",
        "--server.address=0.0.0.0",
        "--server.fileWatcherType=poll"
      ]

  airflow-webserver:
    ports:
      - "${AIRFLOW_PORT}:8080"
    environment:
      PYTHONPATH: /opt/project/src:/opt/project
      AIRFLOW__CORE__HOSTNAME_CALLABLE: airflow.utils.net.get_host_ip_address

  airflow-scheduler:
    environment:
      PYTHONPATH: /opt/project/src:/opt/project
      AIRFLOW__CORE__HOSTNAME_CALLABLE: airflow.utils.net.get_host_ip_address

  airflow-init:
    environment:
      PYTHONPATH: /opt/project/src:/opt/project
      AIRFLOW__CORE__HOSTNAME_CALLABLE: airflow.utils.net.get_host_ip_address

  mlflow:
    ports:
      - "${MLFLOW_PORT}:5000"

  grafana:
    ports:
      - "${GRAFANA_PORT}:3000"

  prometheus:
    ports:
      - "${PROMETHEUS_PORT}:9090"
