x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__DAGS_FOLDER: /opt/project/dags
  MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
  MLFLOW_EXPERIMENT: ${MLFLOW_EXPERIMENT}
  MLFLOW_MODEL_NAME: ${MLFLOW_MODEL_NAME}


x-airflow-common: &airflow-common
  build:
    context: ..
    dockerfile: deployments/airflow/Dockerfile.airflow
  restart: always
  env_file:
    - .env
  environment:
    <<: *airflow-env
  depends_on:
    - postgres
  volumes:
    - airflow_home:/opt/airflow
    - ..:/opt/project
    - ../mlflow_server:/mlflow_server

# service ml flow

services:
  mlflow:
    build:
      context: ..
      dockerfile: deployments/mlflow/Dockerfile.mlflow
    ports:
      - "${MLFLOW_PORT}:5000"
    environment:
      MLFLOW_EXPERIMENT: ${MLFLOW_EXPERIMENT}
      MLFLOW_MODEL_NAME: ${MLFLOW_MODEL_NAME}
    volumes:
      - ../mlflow_server:/mlflow_server
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow_server/mlflow.db
      --artifacts-destination /mlflow_server/artifacts
      --serve-artifacts
      --allowed-hosts '*'

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db:/var/lib/postgresql/data

# SERVICEs AIRFLOW

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    restart: always
    ports:
      - "${AIRFLOW_PORT}:8080"
    environment:
      <<: *airflow-env
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"

volumes:
  airflow_db:
  airflow_home:


  # api:
  #   build:
  #     context: .
  #     dockerfile: api/Dockerfile 
  #   deploy:
  #     replicas: 3 
  #   expose:
  #     - "8000"


  # nginx:
  #   build:
  #     context: deployments/nginx/
  #     dockerfile: Dockerfile
  #   container_name: nginx_revproxy
  #   ports:
  #     - "8080:80"
  #     - "443:443"
  #   volumes:
  #     - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./deployments/nginx/certs:/etc/nginx/certs:ro
  #     - ./deployments/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
  #   depends_on:
  #     - api

  # nginx_exporter:
  #   image: nginx/nginx-prometheus-exporter:latest
  #   container_name: nginx_exporter
  #   ports:
  #     - "9113:9113"
  #   depends_on:
  #     - nginx
  #   environment:
  #     SCRAPE_URI: https://nginx/nginx_status

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus_server
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #     - prometheus_data:/prometheus
  #   depends_on:
  #     - nginx_exporter

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana_dashboard
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   depends_on:
  #     - prometheus
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin

# volumes:
#   airflow_db:
#   airflow_home:
  # prometheus_data:
  # grafana_data: