{
 "title": "Performance",
 "refresh": "10s",
 "panels": [
  {
   "title": "Taux de requêtes par endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(api_requests_total[30m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Latence P95 par endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_request_duration_seconds_bucket[5m])) by (endpoint, le))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Taux d'erreur par endpoint et code HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by (endpoint, status_code) (api_requests_total{status_code!=\"200\"})",
     "legendFormat": "{{endpoint}} {{status_code}}"
    }
   ]
  }
 ]
}